### ISSUE TITLE
Tracking Issue: Improve our CI

### ISSUE THREAD

**Issue by Histalek** [TTT-2/TTT2#1191]
Our CI can be improved in many aspects.
This issue should track all **ideas** we can come up with and their respective progress.

## Pull Requests

- [ ] Check all files against the [workshop addon whitelist](https://github.com/Facepunch/gmad/blob/master/include/AddonWhiteList.h)
- [ ] Check all referenced files (e.g. `Material()` calls) for inclusion in the project and if they are added to the force-download
- [ ] Make extensive use of the [Lua Language Server](https://github.com/LuaLS/lua-language-server) and use it to find common errors
	- this is blocked until we switch our code comments to the LLS annotations
- [ ] Keep language files tidy with our [language parser](https://github.com/TTT-2/ttt2-language_parser)
- [ ] Keep a consistent code style with [stylua](https://github.com/JohnnyMorganz/StyLua)
	- evaluate how this would interact with our current glualint ci 

## Release

(Maybe automate the whole release process on the github side of things?)
- [ ] Generate the html in `cl_changes.lua` from the Changelog
- [ ] Draft a Pre-Release with the Changes from the Changelog

## Other

- [ ] Use [stale action](https://github.com/actions/stale) instead of the old unmaintained project
	- this should also be reconfigured to only mark issues with the label `status / needs info` as stale
	- if possible: it should ping project members instead of marking something as stale, in all other cases

**Comment by TimGoll** [comment]
> * Check all referenced files (e.g. `Material()` calls) for inclusion in the project and if they are added to the force-download

we should probably have a table with the file names that can be iterated by a loop that calls AddFile

**Comment by xopez** [comment]
> * [ ]  Keep a consistent code style with [stylua](https://github.com/JohnnyMorganz/StyLua)

If stylua works great maybe we should recommend the VS Code Extension in this repository.
Maybe you wanna think about that. 
Extension: https://marketplace.visualstudio.com/items?itemName=JohnnyMorganz.stylua
Guide: https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions

**Comment by Histalek** [comment]
> > * [ ]   Keep a consistent code style with [stylua](https://github.com/JohnnyMorganz/StyLua)
> 
> If stylua works great maybe we should recommend the VS Code Extension in this repository. Maybe you wanna think about that. Extension: [marketplace.visualstudio.com/items?itemName=JohnnyMorganz.stylua](https://marketplace.visualstudio.com/items?itemName=JohnnyMorganz.stylua) Guide: [code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)

Yes good point, i'll probably will add a few things to the [CONTRIBUTING.md](https://github.com/TTT-2/TTT2/blob/master/CONTRIBUTING.md) or maybe add some other document that show 1 or 2 example code-editor setups.

**Comment by TimGoll** [comment]
> Check all referenced files (e.g. Material() calls) for inclusion in the project and if they are added to the force-download

might be obsolete by now

**Comment by Histalek** [comment]
> > Check all referenced files (e.g. Material() calls) for inclusion in the project and if they are added to the force-download
> 
> might be obsolete by now

obsolete in which way exactly? we still have a lot of `Material()` calls.
